const DB_URL='https://raw.githubusercontent.com/ARARAT33/AWEArchiveDB/refs/heads/main/a2zdb.json';
const state={ideas:[],filtered:[]};
const fallbackCategories=['Technology','Science','Business','Education','Design','Society','Environment','Culture','Health','Other'];
const $=s=>document.querySelector(s);
async function load(){try{const r=await fetch(DB_URL,{cache:'no-store'});const raw=await r.json();state.ideas=normalize(raw)}catch(e){state.ideas=[]}buildCategories();render();}
function normalize(raw){let a=Array.isArray(raw)?raw:(raw.ideas||raw.data||raw.items||[]);return a.map((x,i)=>({id:x.id||String(i+1),title:x.title||x.name||'Untitled idea',idea:x.idea||x.description||x.content||x.text||'',category:x.category||x.type||'Other',author:x.author||x.name||'Anonymous',created:x.created||x.date||x.createdAt||null}));}
function cats(){return [...new Set([...fallbackCategories,...state.ideas.map(x=>x.category).filter(Boolean)])]}
function buildCategories(){const cs=cats();$('#category').innerHTML='<option value="all">All categories</option>'+cs.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('#formCategory').innerHTML=cs.map(c=>`<option>${esc(c)}</option>`).join('');$('#catCount').textContent=cs.length;$('#count').textContent=state.ideas.length;$('#categoryGrid').innerHTML=cs.map(c=>`<button class="category glass" data-cat="${esc(c)}"><b>${icon(c)} &nbsp;${esc(c)}</b><span>${state.ideas.filter(x=>x.category===c).length} ideas</span></button>`).join('');document.querySelectorAll('.category').forEach(b=>b.onclick=()=>{$('#category').value=b.dataset.cat;render();location.hash='ideas'});}
function render(){let q=$('#search').value.trim().toLowerCase(),c=$('#category').value,s=$('#sort').value;a=state.ideas.filter(x=>(c==='all'||x.category===c)&&(!q||`${x.title} ${x.idea} ${x.category}`.toLowerCase().includes(q)));a.sort((x,y)=>s==='az'?x.title.localeCompare(y.title):s==='old'?date(x.created)-date(y.created):date(y.created)-date(x.created));state.filtered=a;$('#ideaGrid').innerHTML=a.map((x,i)=>`<article class="idea glass" data-id="${esc(x.id)}"><div class="idea-symbol">${icon(x.category)}</div><div class="idea-top"><span>${esc(x.category)}</span><span>${x.author==='Anonymous'?'ANONYMOUS':'CONTRIBUTOR'}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.idea).slice(0,180)}${x.idea.length>180?'…':''}</p><span class="pill">READ IDEA →</span></article>`).join('');$('#empty').hidden=a.length!==0;document.querySelectorAll('.idea').forEach(el=>el.onclick=()=>showIdea(el.dataset.id));}
function showIdea(id){const x=state.ideas.find(i=>i.id===id);if(!x)return;const m=$('#submitModal');m.classList.add('open');m.setAttribute('aria-hidden','false');m.querySelector('.eyebrow').textContent=x.category.toUpperCase()+' · A2Z ARCHIVE';m.querySelector('h2').textContent=x.title;m.querySelector('.modal-note').textContent=x.idea+(x.author?'\n\n— '+x.author:'');$('#ideaForm').style.display='none';$('#closeModal').onclick=closeModal;}
function closeModal(){$('#submitModal').classList.remove('open');$('#ideaForm').style.display='block';$('#formStatus').textContent='';$('#submitModal').querySelector('.eyebrow').textContent='ADD TO A2Z';$('#submitModal').querySelector('h2').textContent='Share an idea.';$('#submitModal').querySelector('.modal-note').textContent='Your name is optional. Contributions are intended to be freely reusable by everyone.'}
function date(v){const n=Date.parse(v||'');return Number.isFinite(n)?n:0}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function icon(c){return ({Technology:'⌘',Science:'◌',Business:'↗',Education:'⌘',Design:'✦',Society:'◎',Environment:'♧',Culture:'◈',Health:'＋'})[c]||'◇'}
document.querySelectorAll('.open-submit').forEach(b=>b.onclick=()=>{closeModal();$('#submitModal').classList.add('open')});$('#closeModal').onclick=closeModal;document.querySelector('.modal-backdrop').onclick=closeModal;$('#search').oninput=render;$('#category').onchange=render;$('#sort').onchange=render;$('#randomBtn').onclick=()=>{if(!state.ideas.length)return;showIdea(state.ideas[Math.floor(Math.random()*state.ideas.length)].id)};
$('#ideaForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const status=$('#formStatus');status.textContent='Publishing…';const payload={title:f.get('title'),idea:f.get('idea'),category:f.get('category'),anonymous:f.get('anonymous')==='on',freeuse:true};try{const r=await fetch('/api/ideas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());status.textContent='Published successfully. Thank you for adding to A2Z.';e.target.reset();f.get('anonymous');}catch(err){status.textContent='Could not publish right now. Please try again later.';console.error(err)}};
load();
