const DB_URL='https://raw.githubusercontent.com/ARARAT33/AWEArchiveDB/refs/heads/main/a2zdb.json';
const PUBLISH_LIMIT=100000;
const state={ideas:[],filtered:[]};
const fallbackCategories=['Technology','Science','Business','Education','Design','Society','Environment','Culture','Health','Arts','Media','Architecture','Transport','Energy','Space','Food','Agriculture','Finance','Gaming','AI','Robotics','Security','Community','Government','Future','Other'];
const $=s=>document.querySelector(s);
async function load(){try{const r=await fetch(DB_URL,{cache:'no-store'});if(!r.ok)throw 0;const raw=await r.json();state.ideas=normalize(raw)}catch(e){state.ideas=[]}buildCategories();updateCapacity();render()}
function normalize(raw){let a=Array.isArray(raw)?raw:(raw.ideas||raw.data||raw.items||[]);return a.map((x,i)=>({id:x.id||String(i+1),title:x.title||x.name||'Untitled idea',idea:x.idea||x.description||x.content||x.text||'',category:x.category||x.type||'Other',author:x.anonymous?'Anonymous':(x.author||'Anonymous'),created:x.created||x.date||x.createdAt||null}))}
function todayCount(){const d=new Date().toISOString().slice(0,10);return state.ideas.filter(x=>String(x.created||'').slice(0,10)===d).length}
function updateCapacity(){const n=todayCount(),remaining=Math.max(0,PUBLISH_LIMIT-n),bar=$('#capacityBar'),count=$('#todayCount'),remain=$('#remainingCount'),note=$('#capacityNote');if(count)count.textContent=n.toLocaleString();if(remain)remain.textContent=remaining.toLocaleString();if(bar)bar.style.width=Math.min(100,n/PUBLISH_LIMIT*100)+'%';if(note)note.textContent=n>=PUBLISH_LIMIT?'Publishing is closed for today. The daily limit resets automatically.':'Publishing is open.';document.querySelectorAll('.open-submit').forEach(b=>b.disabled=n>=PUBLISH_LIMIT)}
function cats(){return [...new Set([...fallbackCategories,...state.ideas.map(x=>x.category).filter(Boolean)])]}
function buildCategories(){const cs=cats();$('#category').innerHTML='<option value="all">All categories</option>'+cs.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('#formCategory').innerHTML=cs.map(c=>`<option>${esc(c)}</option>`).join('');$('#catCount').textContent=cs.length;$('#count').textContent=state.ideas.length.toLocaleString();$('#categoryGrid').innerHTML=cs.map(c=>`<button class="category glass" data-cat="${esc(c)}"><b>${icon(c)} &nbsp;${esc(c)}</b><span>${state.ideas.filter(x=>x.category===c).length} ideas</span></button>`).join('');document.querySelectorAll('.category').forEach(b=>b.onclick=()=>{$('#category').value=b.dataset.cat;render();location.hash='ideas'})}
function render(){let q=$('#search').value.trim().toLowerCase(),c=$('#category').value,s=$('#sort').value;let a=state.ideas.filter(x=>(c==='all'||x.category===c)&&(!q||`${x.title} ${x.idea} ${x.category}`.toLowerCase().includes(q)));a.sort((x,y)=>s==='az'?x.title.localeCompare(y.title):s==='old'?date(x.created)-date(y.created):date(y.created)-date(x.created));state.filtered=a;$('#ideaGrid').innerHTML=a.map(x=>`<article class="idea glass" data-id="${esc(x.id)}"><div class="idea-symbol">${icon(x.category)}</div><div class="idea-top"><span>${esc(x.category)}</span><span>ID ${esc(x.id)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.idea).slice(0,180)}${x.idea.length>180?'…':''}</p><span class="pill">OPEN IDEA PAGE →</span></article>`).join('');$('#empty').hidden=a.length!==0;document.querySelectorAll('.idea').forEach(el=>el.onclick=()=>location.href='idea.html?id='+encodeURIComponent(el.dataset.id))}
function showIdea(id){location.href='idea.html?id='+encodeURIComponent(id)}
function closeModal(){$('#submitModal').classList.remove('open');$('#ideaForm').style.display='block';$('#formStatus').textContent='';$('#submitModal').querySelector('.eyebrow').textContent='ADD TO A2Z';$('#submitModal').querySelector('h2').textContent='Share an idea.'}
function date(v){const n=Date.parse(v||'');return Number.isFinite(n)?n:0}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function icon(c){return ({Technology:'⌘',Science:'◌',Business:'↗',Education:'▣',Design:'✦',Society:'◎',Environment:'♧',Culture:'◈',Health:'＋',Arts:'✧',Media:'◍',Architecture:'⌂',Transport:'➜',Energy:'ϟ',Space:'✺',Food:'◇',Agriculture:'♧',Finance:'◒',Gaming:'✦',AI:'✺',Robotics:'⚙',Security:'◉',Community:'○',Government:'⌘',Future:'∞'})[c]||'◇'}
document.querySelectorAll('.open-submit').forEach(b=>b.onclick=()=>{if(todayCount()>=PUBLISH_LIMIT){$('#formStatus').textContent='Today’s publishing limit has been reached. Please wait for the reset.';return}closeModal();$('#submitModal').classList.add('open');$('#submitModal').setAttribute('aria-hidden','false')});$('#closeModal').onclick=closeModal;document.querySelector('.modal-backdrop').onclick=closeModal;$('#search').oninput=render;$('#category').onchange=render;$('#sort').onchange=render;$('#randomBtn').onclick=()=>{if(state.ideas.length)showIdea(state.ideas[Math.floor(Math.random()*state.ideas.length)].id)};
$('#ideaForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),status=$('#formStatus');if(todayCount()>=PUBLISH_LIMIT){status.textContent='The daily A2Z publishing limit of 100,000 has been reached. Publishing is closed until the next reset.';return}status.textContent='Publishing…';const payload={title:String(f.get('title')||'').trim(),idea:String(f.get('idea')||'').trim(),category:String(f.get('category')||'Other'),anonymous:true,freeuse:f.get('freeuse')==='on'};if(payload.title.length<2||payload.idea.length<20){status.textContent='Please provide a clear title and at least 20 characters of idea text.';return}try{const r=await fetch('/api/ideas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'publish failed');status.textContent=`Published as Idea ID ${data.id}.`;setTimeout(()=>location.href='idea.html?id='+encodeURIComponent(data.id),700)}catch(err){status.textContent=err.message||'Could not publish right now. Please try again later.';console.error(err)}};
load();
